package Login;

/**
* LoginHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votaciones.idl
* martes 5 de junio de 2018 10:33:48 PM CDT
*/


// votaciones.idl
abstract public class LoginHelper
{
  private static String  _id = "IDL:Login:1.0";

  public static void insert (org.omg.CORBA.Any a, Login that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Login extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LoginHelper.id (), "Login");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Login read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LoginStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Login value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Login narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Login)
      return (Login)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LoginStub stub = new _LoginStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Login unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Login)
      return (Login)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LoginStub stub = new _LoginStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
