package Login;

/**
* LoginPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votaciones.idl
* martes 5 de junio de 2018 10:36:12 PM CDT
*/


// votaciones.idl
public abstract class LoginPOA extends org.omg.PortableServer.Servant
 implements LoginOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("registrar", new java.lang.Integer (1));
    _methods.put ("vote", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Login/login
       {
         String user = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.login (user, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Login/registrar
       {
         String nombre = in.read_string ();
         String paterno = in.read_string ();
         String materno = in.read_string ();
         String user = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.registrar (nombre, paterno, materno, user, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Login/vote
       {
         String user = in.read_string ();
         String candidato = in.read_string ();
         this.vote (user, candidato);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Login:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Login _this() 
  {
    return LoginHelper.narrow(
    super._this_object());
  }

  public Login _this(org.omg.CORBA.ORB orb) 
  {
    return LoginHelper.narrow(
    super._this_object(orb));
  }


} // class LoginPOA
