package Login;

/**
* Login.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votaciones.idl
* martes 5 de junio de 2018 10:36:12 PM CDT
*/


// votaciones.idl
public interface Login extends LoginOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Login
