package Cliente;

import java.awt.Color;
import javax.swing.JFrame;

public class informacionAnaya extends javax.swing.JFrame {

    public informacionAnaya() {
        initComponents();
        getContentPane().setBackground(new Color(254,254,254));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelEstudios = new javax.swing.JPanel();
        etiquetaEstudios = new javax.swing.JLabel();
        textoEstudios = new javax.swing.JTextArea();
        panelPropuestas = new javax.swing.JPanel();
        etiquetaPropuestas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoPropuestas = new javax.swing.JTextArea();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setLocation(new java.awt.Point(50, 10));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        panelInfo.setBackground(getBackground());
        panelInfo.setPreferredSize(new java.awt.Dimension(580, 100));
        panelInfo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel1.setBackground(getBackground());
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nombre:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 20));
        panelInfo.add(jLabel1);

        jLabel2.setBackground(getBackground());
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Ricardo Anaya Cortés");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(470, 20));
        panelInfo.add(jLabel2);

        jLabel3.setBackground(getBackground());
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Alias:");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));
        panelInfo.add(jLabel3);

        jLabel4.setBackground(getBackground());
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Anaya");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 20));
        panelInfo.add(jLabel4);

        jLabel5.setBackground(getBackground());
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fecha de nacimiento:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(190, 20));
        panelInfo.add(jLabel5);

        jLabel6.setBackground(getBackground());
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("25 de Febrero de 1979 (39 años)");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(360, 20));
        panelInfo.add(jLabel6);

        getContentPane().add(panelInfo);

        panelEstudios.setBackground(getBackground());
        panelEstudios.setPreferredSize(new java.awt.Dimension(580, 100));
        panelEstudios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        etiquetaEstudios.setBackground(getBackground());
        etiquetaEstudios.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        etiquetaEstudios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaEstudios.setText("Estudios:");
        etiquetaEstudios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiquetaEstudios.setOpaque(true);
        etiquetaEstudios.setPreferredSize(new java.awt.Dimension(100, 20));
        panelEstudios.add(etiquetaEstudios);

        textoEstudios.setEditable(false);
        textoEstudios.setBackground(getBackground());
        textoEstudios.setColumns(30);
        textoEstudios.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        textoEstudios.setLineWrap(true);
        textoEstudios.setRows(3);
        textoEstudios.setText("Licenciatura en Derecho en la Universidad Autónoma de Querétaro.\nMaestría en Derecho Fiscal en la Universidad del Valle de México.\nDoctorado en Ciencias Políticas y Sociales en la UNAM.");
        textoEstudios.setWrapStyleWord(true);
        textoEstudios.setBorder(null);
        textoEstudios.setFocusable(false);
        textoEstudios.setPreferredSize(new java.awt.Dimension(570, 70));
        textoEstudios.setRequestFocusEnabled(false);
        textoEstudios.setVerifyInputWhenFocusTarget(false);
        panelEstudios.add(textoEstudios);

        getContentPane().add(panelEstudios);

        panelPropuestas.setBackground(getBackground());
        panelPropuestas.setPreferredSize(new java.awt.Dimension(580, 410));
        panelPropuestas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        etiquetaPropuestas.setBackground(getBackground());
        etiquetaPropuestas.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        etiquetaPropuestas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaPropuestas.setText("Propuestas:");
        etiquetaPropuestas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiquetaPropuestas.setOpaque(true);
        etiquetaPropuestas.setPreferredSize(new java.awt.Dimension(200, 20));
        panelPropuestas.add(etiquetaPropuestas);

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(570, 365));

        textoPropuestas.setEditable(false);
        textoPropuestas.setBackground(getBackground());
        textoPropuestas.setColumns(30);
        textoPropuestas.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        textoPropuestas.setLineWrap(true);
        textoPropuestas.setRows(3);
        textoPropuestas.setText("• Creación de un Ingreso Básico Universal (IBU) con el objetivo de reducir la desigualdad y erradicar la pobreza extrema en el país.\n• Además de acabar con la corrupción y la impunidad y recuperar la paz y la seguridad, Anaya ha propuesto reducir el número de funcionarios públicos y ayudar a los emprendedores.\n• Propuesta: “Dotar a la Auditoría Superior de la Federación (ASF) de autonomía constitucional plena, e integrarla con profesionistas de sobrada solvencia moral, buena reputación, capacidad técnica e independencia y dotar al nuevo organismo de un alcance nacional, para castigar desvíos de recursos no sólo de origen federal sino local”.\n• Propuesta: “Obligar a todos los servidores públicos a presentar sus declaraciones de intereses, fiscal y patrimonial”.\n• Desmantelar a las organizaciones criminales y mantener a las fuerzas armadas en las calles.\n• Legislar la revocación de mandato.\n• Gobierno de coalición en la que el presidente rinda cuentas al Congreso.\n• Reformar el artículo 108 constitucional para que el presidente sea juzgado por corrupción.\n• Prensa libre y sociedad fuerte.\n• Eliminar uso de efectivo en las transacciones del gobierno.\n• Reconocer la deuda histórica con los pueblos indígenas, migrantes, los excluidos por alguna discapacidad y los niños que se van a dormir con hambre.");
        textoPropuestas.setToolTipText("");
        textoPropuestas.setWrapStyleWord(true);
        textoPropuestas.setBorder(null);
        textoPropuestas.setFocusable(false);
        textoPropuestas.setOpaque(false);
        textoPropuestas.setPreferredSize(new java.awt.Dimension(550, 460));
        textoPropuestas.setRequestFocusEnabled(false);
        textoPropuestas.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(textoPropuestas);

        panelPropuestas.add(jScrollPane1);

        getContentPane().add(panelPropuestas);

        botonRegresar.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacionAnaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacionAnaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacionAnaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacionAnaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacionAnaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel etiquetaEstudios;
    private javax.swing.JLabel etiquetaPropuestas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelEstudios;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPropuestas;
    private javax.swing.JTextArea textoEstudios;
    private javax.swing.JTextArea textoPropuestas;
    // End of variables declaration//GEN-END:variables
}
