package Cliente;

import java.awt.Color;
import javax.swing.JFrame;

public class informacionAmlo extends javax.swing.JFrame {

    /**
     * Creates new form informacionAmlo
     */
    public informacionAmlo() {
        initComponents();
        getContentPane().setBackground(new Color(254,254,254));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelEstudios = new javax.swing.JPanel();
        etiquetaEstudios = new javax.swing.JLabel();
        textoEstudios = new javax.swing.JTextArea();
        panelPropuestas = new javax.swing.JPanel();
        etiquetaPropuestas = new javax.swing.JLabel();
        textoPropuestas = new javax.swing.JTextArea();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setLocation(new java.awt.Point(300, 10));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        panelInfo.setBackground(getBackground());
        panelInfo.setPreferredSize(new java.awt.Dimension(580, 100));
        panelInfo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel1.setBackground(getBackground());
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nombre:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 20));
        panelInfo.add(jLabel1);

        jLabel2.setBackground(getBackground());
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Andrés Manuel López Obrador");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(470, 20));
        panelInfo.add(jLabel2);

        jLabel3.setBackground(getBackground());
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Alias:");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));
        panelInfo.add(jLabel3);

        jLabel4.setBackground(getBackground());
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("AMLO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 20));
        panelInfo.add(jLabel4);

        jLabel5.setBackground(getBackground());
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fecha de nacimiento:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(190, 20));
        panelInfo.add(jLabel5);

        jLabel6.setBackground(getBackground());
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("13 de Noviembre de 1953 (64 años)");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(360, 20));
        panelInfo.add(jLabel6);

        getContentPane().add(panelInfo);

        panelEstudios.setBackground(getBackground());
        panelEstudios.setPreferredSize(new java.awt.Dimension(580, 90));
        panelEstudios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        etiquetaEstudios.setBackground(getBackground());
        etiquetaEstudios.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        etiquetaEstudios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaEstudios.setText("Estudios:");
        etiquetaEstudios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiquetaEstudios.setOpaque(true);
        etiquetaEstudios.setPreferredSize(new java.awt.Dimension(100, 20));
        panelEstudios.add(etiquetaEstudios);

        textoEstudios.setEditable(false);
        textoEstudios.setBackground(getBackground());
        textoEstudios.setColumns(30);
        textoEstudios.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        textoEstudios.setLineWrap(true);
        textoEstudios.setRows(2);
        textoEstudios.setText("Estudió la licenciatura de Ciencias Políticas y Administración Pública en la Universidad Nacional Autónoma de México (UNAM) de 1973 a 1976.");
        textoEstudios.setWrapStyleWord(true);
        textoEstudios.setBorder(null);
        textoEstudios.setFocusable(false);
        textoEstudios.setPreferredSize(new java.awt.Dimension(570, 40));
        textoEstudios.setRequestFocusEnabled(false);
        textoEstudios.setVerifyInputWhenFocusTarget(false);
        panelEstudios.add(textoEstudios);

        getContentPane().add(panelEstudios);

        panelPropuestas.setBackground(getBackground());
        panelPropuestas.setPreferredSize(new java.awt.Dimension(580, 410));
        panelPropuestas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        etiquetaPropuestas.setBackground(getBackground());
        etiquetaPropuestas.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        etiquetaPropuestas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaPropuestas.setText("Propuestas:");
        etiquetaPropuestas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiquetaPropuestas.setOpaque(true);
        etiquetaPropuestas.setPreferredSize(new java.awt.Dimension(200, 20));
        panelPropuestas.add(etiquetaPropuestas);

        textoPropuestas.setEditable(false);
        textoPropuestas.setBackground(getBackground());
        textoPropuestas.setColumns(30);
        textoPropuestas.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        textoPropuestas.setLineWrap(true);
        textoPropuestas.setRows(3);
        textoPropuestas.setText("•  Eliminar los fueros que protegen a los altos funcionarios, incluido el presidente.\n•  Echar para atrás las reformas del actual gobierno.\n•  Revisar millonarios contratos energéticos y fijar los precios de los productos agrícolas.\n•  Relanzar la Secretaría de Seguridad Pública (eliminada en 2013 por el presidente Enrique Peña Nieto) y fusionar a la Policía, la Marina y el Ejército en una “Guardia Nacional”.\n•  Iniciativa de reforma constitucional para la revocación de mandato.\n•  Atender las causas de la violencia, en particular de la pobreza.\n•  Convocar a expertos para definir los términos del combate a la inseguridad y la amnistía.\n•  Acabar con la corrupción y gobernar con el ejemplo.\n•  Reducir los sueldos de los de arriba para incrementar los de los de abajo.\n•  Crecimiento económico, creación de más empleos y mayores oportunidades para los jóvenes.\n•  Un acuerdo con el pueblo para que la honestidad sea una forma de vida y de gobierno.");
        textoPropuestas.setToolTipText("");
        textoPropuestas.setWrapStyleWord(true);
        textoPropuestas.setBorder(null);
        textoPropuestas.setFocusable(false);
        textoPropuestas.setOpaque(false);
        textoPropuestas.setPreferredSize(new java.awt.Dimension(570, 365));
        textoPropuestas.setRequestFocusEnabled(false);
        textoPropuestas.setVerifyInputWhenFocusTarget(false);
        panelPropuestas.add(textoPropuestas);

        getContentPane().add(panelPropuestas);

        botonRegresar.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacionAmlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacionAmlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacionAmlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacionAmlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacionAmlo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel etiquetaEstudios;
    private javax.swing.JLabel etiquetaPropuestas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelEstudios;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPropuestas;
    private javax.swing.JTextArea textoEstudios;
    private javax.swing.JTextArea textoPropuestas;
    // End of variables declaration//GEN-END:variables
}
