package Cliente;

import Login.Login;
import com.dropbox.core.DbxException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class InicioSesion extends javax.swing.JPanel {

    private Login login;
    private JFrame frame;
    
    public InicioSesion(Login login){
        this.login = login;
        initComponents();
        frame = new JFrame("Iniciar sesión");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 200);
        frame.getContentPane().setBackground(new java.awt.Color(235, 240, 169));
        frame.add(this);
        frame.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        labelContrasena = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        panelBotones = new javax.swing.JPanel();
        botonIniciar = new javax.swing.JButton();
        botonNuevaCuenta = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 240, 169));
        setPreferredSize(new java.awt.Dimension(350, 100));
        setLayout(new java.awt.BorderLayout());

        panelTexto.setBackground(getBackground());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        jLabel1.setText("Iniciar sesión");
        panelTexto.add(jLabel1);

        add(panelTexto, java.awt.BorderLayout.NORTH);

        panelDatos.setBackground(getBackground());
        panelDatos.setPreferredSize(new java.awt.Dimension(200, 80));
        panelDatos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        labelUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsuario.setText("Usuario:");
        labelUsuario.setPreferredSize(new java.awt.Dimension(90, 40));
        panelDatos.add(labelUsuario);

        textUsuario.setColumns(15);
        textUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        panelDatos.add(textUsuario);

        labelContrasena.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelContrasena.setText("Contraseña:");
        labelContrasena.setPreferredSize(new java.awt.Dimension(90, 40));
        panelDatos.add(labelContrasena);

        textPassword.setColumns(15);
        textPassword.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        panelDatos.add(textPassword);

        add(panelDatos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(getBackground());
        panelBotones.setPreferredSize(new java.awt.Dimension(350, 40));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        botonIniciar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botonIniciar.setText("Iniciar Sesion");
        botonIniciar.setName("iniciar"); // NOI18N
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panelBotones.add(botonIniciar);

        botonNuevaCuenta.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botonNuevaCuenta.setText("Crear cuenta");
        botonNuevaCuenta.setName("nuevo"); // NOI18N
        botonNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaCuentaActionPerformed(evt);
            }
        });
        panelBotones.add(botonNuevaCuenta);

        botonCancelar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setName("cancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        add(panelBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        String user = textUsuario.getText();
        String pass = textPassword.getText();
        
        String result = login.login(user, pass);
        votacionesGUI votaciones = null;
        
        switch(result){
            case "OK":
        {
            try {
                votaciones = new votacionesGUI(login, false, user);
            } catch (DbxException ex) {}
        }
                votaciones.setVisible(true);
                frame.dispose();
                break;
            case "Voted":
        {
            try {
                votaciones = new votacionesGUI(login, true, user);
            } catch (DbxException ex) {}
        }
                votaciones.setVisible(true);
                frame.dispose();
                break;
            case "Invalid":
                JOptionPane.showMessageDialog(null, "Usuario/Contraseña incorrecto");
                break;
        }
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaCuentaActionPerformed
        new crearCuenta(login).setVisible(true);
    }//GEN-LAST:event_botonNuevaCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonNuevaCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTexto;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the textPassword
     */
    public javax.swing.JPasswordField getTextPassword() {
        return textPassword;
    }

    /**
     * @return the textUsuario
     */
    public javax.swing.JTextField getTextUsuario() {
        return textUsuario;
    }
}
